name: Build and deploy docs

on:
  workflow_call:
    inputs:
      runs-on-group:
        required: true
        type: string
    secrets:
      CHECKOUT_TOKEN:
        required: true

jobs:
  build-and-deploy-docs:
    runs-on:
      group: ${{ inputs.runs-on-group }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - name: Build tt-metal
        run: make build
      - name: Activate and build docs
        run: |
          source build/python_env/bin/activate
          cd docs/
          make html
      - name: Move built docs to server
        run: |
          rm -rf ~/docsdeploy/tt-metal/docs/build/html
          cp -r docs/build/html ~/tt-metal/docs/build/
