name: eager - Package

on:
  workflow_call:
    inputs:
      environment:
        required: True
        type: string
      os:
        required: True
        type: string
      arch:
        required: True
        type: string
    secrets:
      CHECKOUT_TOKEN:
        required: True

jobs:
  build-eager-package:
    runs-on: ${{ inputs.os }}
    environment: ${{ inputs.environment }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ inputs.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
          fetch-depth: 0
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ${{ inputs.os }}
      - uses: ./.github/actions/install-metal-dev-deps
        with:
          os: ${{ inputs.os }}
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Create dev environment for packaging
        run: make python_env/dev
      - name: Build Python package distribution
        run: |
          source build/python_env/bin/activate
          python -m build
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v3
        with:
          name: eager-dist-${{ inputs.os }}-${{ inputs.arch }}
          path: dist/
