name: Scheduled build and run all regressions and models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build-and-test-all:
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
    environment: dev
    runs-on: model-runner
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Run clean + build + all reg tests scripts
        run: ./tests/scripts/run_reg_scripts.sh
